---
# Disable default keybindings
"editor_view:cut_all_right": none
"editor_view:insert_newline": none
"input:clear_screen": none
"workspace:toggle_ai_assistant": none
"editor_view:backspace": none

# pane navigation
"pane_group:navigate_down": ctrl-j
"pane_group:navigate_right": ctrl-l
"pane_group:navigate_up": ctrl-k
"pane_group:navigate_left": ctrl-h
